#!/usr/bin/env python3

import requests
import lxml.html
import re
import datetime
from sqlite3 import dbapi2 as sqlite

DB = 'cached.db'
SQL = """INSERT INTO cases_log (day, cases) VALUES (?, ?);"""
URL = 'https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public'

pattern = r'^As of 9am on (.*2020),.*and ([0-9]+) were confirmed as positive'

def get_date_and_count():
    req = requests.get(URL)
    root = lxml.html.fromstring(req.text)
    headings = root.xpath("//h2[@id = '%s']" % 'number-of-cases')
    matching_h2 = headings[0]
    siblings = [ elt for elt in matching_h2.itersiblings() ]
    tgt = siblings[0]
    # probably could have done that all with xpath

    text = tgt.text

    regexp = re.compile(pattern)
    results = regexp.match(text)
    whole, date, count = tuple([ results.group(i) for i in range(0, 3) ])

    day = datetime.datetime.strptime(date, '%d %B %Y')
    return day, int(count)

def run():
    day, count = get_date_and_count()
    day_formatted = datetime.datetime.strftime(day, '%Y-%m-%d')
    db = sqlite.connect(DB)
    c = db.cursor()
    c.execute(SQL, (day_formatted, count))
    db.commit()
    db.close()

if __name__ == '__main__':
   run()
