#!/usr/bin/env python3

import requests
import lxml.html
import re
import datetime
import database
import sys

URL = 'https://gov.uk/guidance/coronavirus-covid-19-information-for-the-public'

pattern = r'^As of 9am on (.*2020),.* ([0-9,]+) were confirmed( as)? positi'

iso_date_fmt = "%Y-%m-%d"

def today_iso():
    return datetime.datetime.now().strftime(iso_date_fmt)

def get_date_and_count():
    req = requests.get(URL)
    root = lxml.html.fromstring(req.text)
    headings = root.xpath("//h2[@id = '%s']" % 'number-of-cases-and-deaths')
    matching_h2 = headings[0]
    siblings = [ elt for elt in matching_h2.itersiblings() ]
    tgt = siblings[0]
    # probably could have done that all with xpath

    text = tgt.text

    regexp = re.compile(pattern)
    results = regexp.match(text)
    # print(text, results)
    whole, date, count = tuple([ results.group(i) for i in range(0, 3) ])

    day = datetime.datetime.strptime(date, '%d %B %Y')
    count = count.replace(",", "")
    return day, int(count)

def run():
    if database.already_done_today(today_iso()):
        print("Data already obtained for today")
        sys.exit(0)
    day, count = get_date_and_count()
    # date_diff = (datetime.datetime.now() - day).days

    day_formatted = datetime.datetime.strftime(day, iso_date_fmt)
    database.save_update(day_formatted, count)

if __name__ == '__main__':
   run()
